name: Mobile Deployment Workflow
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-phone:
    runs-on: ubuntu-latest
    outputs:
      version_name: ${{ steps.extract_version.outputs.version_name }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Add Android SDK tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Install Android Build Tools
        run: |
          sdkmanager --install "build-tools;34.0.0"

      - name: Export ANDROID_SDK_ROOT
        run: echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Add Android SDK tools to PATH
        run: |
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Extract version info from branch
        id: extract_version
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME}"
          VERSION_NAME="${BRANCH_NAME%/release}"
          VERSION_CODE=$(echo $VERSION_NAME | awk -F. '{printf("%03d%03d%03d", $1, $2, $3)}')
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
          echo "version_name=$VERSION_NAME" >> $GITHUB_OUTPUT
        # version code strategy: [1/2][000][000][000] -> [phone/wear][version name]

      - name: Update libs.versions.toml with new versions
        run: |
          sed -i "s/^projectVersionName = .*/projectVersionName = \"${VERSION_NAME}\"/" gradle/libs.versions.toml
          sed -i "s/^projectVersionCode = .*/projectVersionCode = \"1${VERSION_CODE}\"/" gradle/libs.versions.toml
          cat gradle/libs.versions.toml

      - name: Build Mobile prodRelease
        env:
          STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
          STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
        run: ./gradlew :app:bundleRelease
        continue-on-error: false

      - name: Build Mobile and Wear APKs
        run: |
          ./gradlew :app:assembleRelease
          ./gradlew :wear:app:assembleRelease

      - name: Sign Mobile APK
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'


      - name: Sign Wear APK
        uses: r0adkll/sign-android-release@v1
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
        with:
          releaseDirectory: wear/app/build/outputs/apk/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'

      - name: Sign Mobile AAB
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.KEYSTORE }}'
          alias: '${{ secrets.SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'

      - name: Upload Mobile bundle as artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          retention-days: 2
        continue-on-error: false

      - name: Upload Mobile APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-apk
          path: app/build/outputs/apk/release/app-release-unsigned-signed.apk
          retention-days: 2

      - name: Upload Wear APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wear-apk
          path: wear/app/build/outputs/apk/release/app-release-unsigned-signed.apk
          retention-days: 2
  deploy:
    runs-on: ubuntu-latest
    needs: build-phone
    env:
      VERSION_NAME: ${{ needs.build-phone.outputs.version_name }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Read release notes (EN)
        id: release_notes
        run: |
          NOTES="$(cat release-notes/whatsnew-en-US)"
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          echo "$NOTES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Download Mobile bundle
        uses: actions/download-artifact@v4
        with:
          name: app-bundle
          path: ${{ github.workspace }}

      - name: Download Mobile APK
        uses: actions/download-artifact@v4
        with:
          name: mobile-apk
          path: ${{ github.workspace }}/release-assets/mobile/

      - name: Download Wear APK
        uses: actions/download-artifact@v4
        with:
          name: wear-apk
          path: ${{ github.workspace }}/release-assets/wear/


      - name: Debug release-assets contents
        run: |
          echo "== release-assets tree =="
          ls -R release-assets
          mv release-assets/mobile/app-release-unsigned-signed.apk mobile-release.apk
          mv release-assets/wear/app-release-unsigned-signed.apk wear-release.apk
          ls -lh

      - name: Generate SHA-256 checksums
        run: |
          sha256sum mobile-release.apk > mobile-release.apk.sha256
          sha256sum wear-release.apk > wear-release.apk.sha256
          ls -lh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION_NAME }}
          name: BeePadel ${{ env.VERSION_NAME }}
          body: ${{ steps.release_notes.outputs.notes }}
          files: |
            mobile-release.apk
            wear-release.apk
            mobile-release.apk.sha256
            wear-release.apk.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Mobile app to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.SERVICE_ACCOUNT_JSON }}'
          packageName: com.vzkz.beepadel
          releaseFiles: ${{ github.workspace }}/app-release.aab
          track: production
          whatsNewDirectory: release-notes/
